#!/usr/bin/env python3
import rospy
from softgrasp_policy import SoftgraspPolicyActionServer

if __name__ == '__main__':
  rospy.init_node('softgrasp_policy_actionserver')
  exp_dir = rospy.get_param('~exp_dir')
  ckpt_dirname = rospy.get_param('~ckpt_dirname')

  pas = SoftgraspPolicyActionServer(exp_dir, ckpt_dirname)
  pas.run()